<a href="https://colab.research.google.com/github/6X10/advanced-statistical-data-analysis/blob/main/pytorch_tensor_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#세팅
import sys
import numpy as np
import torch #pytorch numpy와 유사.실제로 사용하는 attribute, function 거의 1:1 mapping 되나 이름 등이 다를 수 있음->구글링하세요 

In [5]:
#개발환경 확인
print(sys.version)
print(np.__version__)
print(torch.__version__)

3.7.14 (default, Sep  8 2022, 00:06:44) 
[GCC 7.5.0]
1.21.6
1.12.1+cu113


In [6]:
#사용가능한 gpu 확인
available_gpus = [torch.cuda.device(i) for i in range(torch.cuda.device_count())]
print(available_gpus)

In [8]:
device0=torch.device("cuda:0") #0번째 slot의 gpu 카드를 device0라고 명명

In [10]:
#tensor initialize (standard gaussian에서 2,3,4 shape을 가진 tensor 만듦)
#numpy
a_np = np.random.randn(2,3,4)
#pytorch
b=torch.randn(2,3,4)
#둘다 2X3X4 tensor가 됨

In [36]:
print(a_np)
print(b)

[[[ 0.09604464 -1.12115469 -0.34871721  0.21708943]
  [ 0.76756225  0.32567432  0.22123355 -0.18875871]
  [ 1.65137359 -2.38460932 -0.54649    -1.40944374]]

 [[-0.79184548 -1.45594612 -1.56864535 -0.09558155]
  [ 0.14712749 -1.23370508 -2.69592559 -0.30668969]
  [ 0.2841632   0.07654582 -0.3541687  -0.8542382 ]]]
tensor([[[-1.0452, -0.3664,  0.5274,  0.5042],
         [-0.3513,  0.9132, -0.6652,  0.0483],
         [ 1.1589,  0.3656, -0.8145, -1.6240]],

        [[-0.1911, -0.3909,  0.9556,  0.4355],
         [-0.8347, -0.4704,  1.0164,  0.7201],
         [ 0.0521,  0.9062,  0.8530,  1.2260]]], device='cuda:0')


In [12]:
#type 비교
print(type(a_np))
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [15]:
#numpy로 instance화한 tensor와 pytorch로 instance화한  tensor는 서로 연산이 가능한가?
#print(a_np+b) 연산 안됨

In [37]:
#BUT numpy와 pytorch는 호환성이 좋으므로 연산이 아예 불가능한 건 아님
#1. tensor by numpy 를 tensor by pytorch로 변환
a=torch.tensor(a_np)
print(a+b)

RuntimeError: ignored

In [18]:
#1. tensor by pytorch를 tensor by numpy로 converting
b_np=b.numpy()
print(a_np+b_np)

[[[-0.9491594  -1.48755067  0.17865854  0.72130169]
  [ 0.4162202   1.238831   -0.44398344 -0.14042414]
  [ 2.81026193 -2.01898683 -1.36095773 -3.0334102 ]]

 [[-0.98298696 -1.84679949 -0.61305564  0.33994905]
  [-0.68761231 -1.70410491 -1.67948985  0.41343551]
  [ 0.33627044  0.98273282  0.49879528  0.37177618]]]


In [ ]:
#why numpy로도 가능한 연산을 pytorch 사용해서 연산?
#A. gpu를 활용한 연산 가속도 때문. 

In [19]:
#gpu card 사용량 확인
!nvidia-smi #no running processes found -> gpu 사용량 없음

Thu Sep 22 03:05:47 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [25]:
#tensor를 gpu에 얹어보겠음
b=b.to(device0)
print(b) #device='cuda:0"라는 gpu 카드에 얹어졌음을 의미하는 문구 추가됨

tensor([[[-1.0452, -0.3664,  0.5274,  0.5042],
         [-0.3513,  0.9132, -0.6652,  0.0483],
         [ 1.1589,  0.3656, -0.8145, -1.6240]],

        [[-0.1911, -0.3909,  0.9556,  0.4355],
         [-0.8347, -0.4704,  1.0164,  0.7201],
         [ 0.0521,  0.9062,  0.8530,  1.2260]]], device='cuda:0')


gpu card에 얹은 b와 그렇지 않은 a 연산 가능? 
print(a+b) 불가능

서로 다른 gpu card에 얹은 a, b 연산 가능? 불가능

=> tensor 간의 연산이 가능하려면 같은 device 상에 tensor가 존재해야함

In [26]:
#gpu device에 tensor를 얹었을 때 gpu 사용량의 변화 확안
!nvidia-smi #시스템 명령어의 결과에서 processes를 통해서 어디에서 gpu 사용하고 있는지 확인할 수ㅇ

Thu Sep 22 03:10:43 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    29W /  70W |    610MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [27]:
print(b.shape) #b의 shape확인

torch.Size([2, 3, 4])


In [29]:
print(b.dim()) #3d tensor임

3


In [30]:
#standard gaussian 말고 다른 random sampling
c = torch.zeros(5,4) #5,4 shape의 0행렬
print(c)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [31]:
#모든 entry 1인 tensor
d=torch.ones(5,4)
print(d)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [32]:
#.eye = identity matrix 
e=torch.eye(3) #3*3 identity matrix 만들어줘
print(e)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [33]:
#특정 tensor와 같은 shape을 갖는 0으로 된 tensor 만들기
print(b)
f=torch.zeros_like(b)
print(f) #심지어 gpu에 얹은 특성까지 그대로 가지고 옴

tensor([[[-1.0452, -0.3664,  0.5274,  0.5042],
         [-0.3513,  0.9132, -0.6652,  0.0483],
         [ 1.1589,  0.3656, -0.8145, -1.6240]],

        [[-0.1911, -0.3909,  0.9556,  0.4355],
         [-0.8347, -0.4704,  1.0164,  0.7201],
         [ 0.0521,  0.9062,  0.8530,  1.2260]]], device='cuda:0')
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], device='cuda:0')


In [40]:
#a와 shape이 같으면서 1로 된 tensor 만들기
print(a)
a = a.cpu() #gpu에서 내리기
print(a)
g=torch.ones_like(a)
print(g)

tensor([[[ 0.0960, -1.1212, -0.3487,  0.2171],
         [ 0.7676,  0.3257,  0.2212, -0.1888],
         [ 1.6514, -2.3846, -0.5465, -1.4094]],

        [[-0.7918, -1.4559, -1.5686, -0.0956],
         [ 0.1471, -1.2337, -2.6959, -0.3067],
         [ 0.2842,  0.0765, -0.3542, -0.8542]]], dtype=torch.float64)
tensor([[[ 0.0960, -1.1212, -0.3487,  0.2171],
         [ 0.7676,  0.3257,  0.2212, -0.1888],
         [ 1.6514, -2.3846, -0.5465, -1.4094]],

        [[-0.7918, -1.4559, -1.5686, -0.0956],
         [ 0.1471, -1.2337, -2.6959, -0.3067],
         [ 0.2842,  0.0765, -0.3542, -0.8542]]], dtype=torch.float64)
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=torch.float64)


In [ ]:
#tensor에서 특정 row, column, entry 꺼내오고 싶음 -> 리스트 다루듯이 하면됨
a[0] #0번째 dimension의 모든 entry 가져와라

In [41]:
a[1,2,3] #마지막 value 가져와

tensor(-0.8542, dtype=torch.float64)

In [42]:
a[:,2,:] #특정 dimension의 특정 entry 가져와라

tensor([[ 1.6514, -2.3846, -0.5465, -1.4094],
        [ 0.2842,  0.0765, -0.3542, -0.8542]], dtype=torch.float64)

In [43]:
#pytorch tensor는 mutable = 값을 변경할 수 있음
a[1,2,3] =0
print(a)

tensor([[[ 0.0960, -1.1212, -0.3487,  0.2171],
         [ 0.7676,  0.3257,  0.2212, -0.1888],
         [ 1.6514, -2.3846, -0.5465, -1.4094]],

        [[-0.7918, -1.4559, -1.5686, -0.0956],
         [ 0.1471, -1.2337, -2.6959, -0.3067],
         [ 0.2842,  0.0765, -0.3542,  0.0000]]], dtype=torch.float64)
